# Prior Distributions {#Prior}

::: {.chapterintro data-latex=""}

- Learn different ways of selecting and constructing priors
- Prior distributions used in clinical studies
- Introduction to hierarchical priors for random effects
- Introduction to sparsity promoting prior for Bayesian regression variable selection
:::

<script src="hideOutput.js"></script>

```{r, echo = FALSE, message=FALSE, warning=FALSE}
# Every chapter, we will load all the library we will use at the beginning
# of the chapter. 
library(tidyverse)
library(ggpubr)
library(SHELF)

options(scipen = 999)
```

</br>

## Choosing prios

**Types of prior**

Generally speaking, there are two types of priors: informative and noninformative.

- Priors with information on values of parameters, informative priors

    - Priors that charaterize personal/expert opinion
    - Prior elicitation
    - Historical data or past evidence
    - Default priors in clincial studies
    - Informative priors used for computational efficiency and variable selection
    
- "objective" and non-informative priors

    - Flat prior, vague prior, and weakly-informative priors


**Important consideration before choosing a prior**

- Choice of prior does affect the posterior, however, prior is only one part of Bayesian modelling.
    - Prior is not unique and there is no one "correct" prior distribution!
    - In many situations with large sample sizes, the posterior distribution is not too sensitive to reasonable changes in prior.
    - When working with rare outcomes (e.g., small disease cohort), changes in prior distribution can influence posterior distribution

- One criticism of Bayesian inference is in its incorporation of priors, which is considered as a subjective modelling choice. 
    - However, any statistical analysis is inherently subjective, frequentist or Bayesian.
    - "Subjective" choice of prior can often be **beneficial**
        - Sensitivity analysis is crucial in assessing the impact of particular distributions on the conclusions.
        - when we are working with small samples, informative prior allows us to explicitly incorporate past evidence and expert knowledge
        - we can also use sparsity promoting prior (i.e., shrinkage prior) to reduce the number of parameters to be estimated to improve estimation efficiency and avoid over-fitting
        
### Eliciting priors from experts

Elicitation is the process of

- representing the knowledge of one or more experts - expert knowledge is useful!
- concerning an uncertain quantity as a probability distribution for that quantity (i.e. as a random variable with some distribution)
    
Good elicitation methods are formal, statistically rigorous, and use carefully considered probabilistic judgement techniques

- in practice, elicitation follows pre-developed elicitation protocol

- elicitation process often involve training and discussion between experts and statisticians to eliminate bias, mis-interpretation, over-optimistic thinking ...



**Aggregating expert judgement**

There are two general approaches to summarizing the estimates from the experts.

- Aggregate the distributions
    - Elicit a distribution from each expert separately
    - Combine these multiple distribution using mathematical aggregation, also called "pooling"
    
- Aggregate the experts
    - gather expert belief and elicit a single distribution, also called behavioural aggregation. 

       
        
**Three protocols**

- **Most popular.** Sheffield Elicitation Framework (SHELF). The SHELF protocol is a behavioral aggregation method that uses two rounds of judgments. [@o2006uncertain]
    - In the first round, individuals make private judgements
    - In the second round, those judgments are reviewed before the group agrees on consensus judgement. 

- Cooke protocol. A mathematical aggregation approach weights expert responses by their likely accuracy. [@cooke1991experts]
    - The likely accuracy is calculated using a "seed" value.
    - Expert who more accurately predict the seed value are weighted more.
    
- [Delphi Method](https://www.rand.org/topics/delphi-method.html) The Delphi is similar to SHELF as it is a behavioral aggregation method with two or more rounds except that anonymity is maintained in terms of who gave which answers. 
    - unlike SHELF, experts provide their judgments individually with no interaction and a pooling rule is required across expert final distributions.


Reference reading on expert elicitation: 

- [Methods to elicit beliefs for Bayesian priors: a systematic review (2010), by johnson et al.](https://www.sciencedirect.com/science/article/pii/S0895435609001759?casa_token=hejHbiF8uv4AAAAA:wfJlHvZYsIkhyGIrPooRQuO8Bz57fPoe_wYhUvW4xA02hio_LDCZF8KzGykdotVcPCQSVQchDSs#bib24) [@johnson2010methods] 
    - Reviewed on measurement properties including validity,
reliability, responsiveness, and feasibility (lacking in exisiting work).
    - A valid and reliable method [@johnson2010valid] 

- [Uncertain judgements: eliciting experts' probabilities (2006) by O'Hagan et al.](https://librarysearch.library.utoronto.ca/permalink/01UTORONTO_INST/fedca1/cdi_crossref_primary_10_1007_s11336_007_9036_x) [@o2006uncertain]
    - SHELF documentation and software: http://www.jeremy-oakley.staff.shef.ac.uk/shelf/software/
    - Dr. Anthony O'Hagan's talk on elicitation and SHELF: https://www.youtube.com/embed/cU4Cd8CGiaM



::: {.workedexample data-latex=""}
**Tutorial example on SHELF framework** - Elicitation workshop for Bronchiolitis in Infants Placebo Versus Epinephrine and Dexamethasone (BIPED) study (project manuscript under review)

Principal Investigator for the Elicitation Study: Dr. [Anna Heath](https://www.sickkids.ca/en/staff/h/anna-heath/), PhD, MMath, The Hospital for Sick Children, Toronto

Research Assistant and ShinyApp Developer: [Jingxian (Phebe) Lan](https://www.linkedin.com/in/phebelan/), M.Sc

:::






## Default clincial priors




## Historical data (meta-analysis)



## Hierarchical priors



## Shrinkage priors





    
