--- 
title: "Applied Bayesian Methods in Clinical Epidemiology and Health Care Research"
author: "Kuan Liu and George Tomlinson <br> Institute of Health Policy, Management and Evaluation <br> University of Toronto"
date: "`r Sys.Date()`"
documentclass: krantz
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
colorlinks: yes
lot: no
lof: no
graphics: yes
urlcolor: blue
geometry: "left=1.5in, right=1.5in, top=1.25in, bottom=1.25in"
description: "This is a course note for HAD5314H"
site: bookdown::bookdown_site
always_allow_html: yes
---


# University of Toronto Statement of Acknowledgment of Traditional Land {-}


> "We wish to acknowledge this land on which the University of Toronto operates. For thousands of years it has been the traditional land of the Huron-Wendat, the Seneca, and the Mississaugas of the Credit. Today, this meeting place is still the home to many Indigenous people from across Turtle Island and we are grateful to have the opportunity to work on this land."



# Course Syllabus {-}

## Course Info {-}

_COURSE TITLE_: Applied Bayesian Methods in Clinical Epidemiology and Health Care Research

_SEMESTER_: Winter 2022

_CLASS HOURS AND LOCATION_: TBA

_INSTRUCTORS:_ Kuan Liu and George Tomlinson

_INSTRUCTOR CONTACT INFORMATION_ 

* _EMAIL_: kuan.liu@mail.utoronto.ca 
* _OFFICE HOURS_: TBA
* _OFFICE HOUR LOCATION_: TBA

* _EMAIL_: george.tomlinson@utoronto.ca 
* _OFFICE HOURS_: TBA
* _OFFICE HOUR LOCATION_: TBA

_TEACHING ASSISTANT INFORMATION_: 

* _NAME_: TBA 
* _EMAIL_: TBA
* _OFFICE HOURS_: TBA
* _OFFICE HOUR LOCATION_: TBA
 

## Course Description {-}

This course will introduce students to Bayesian data analysis. After a thorough review of fundamental concepts in statistics and probability, an introduction will be given to the fundamentals of the Bayesian approach, including a look at how computer simulation can be used to solve statistical problems. Students will learn how to use the brms package in the R statistical software environment to carry out Bayesian analyses of data commonly seen in health sciences. Bayesian methods will be covered for binary, continuous and count outcomes in one and two samples, for logistic, linear and Poisson regression, and for meta-analysis. 

By the end of this course, students will:

1 Understand what is meant by a “Bayesian Analysis” and how it differs from a typical analysis under the frequentist framework
2 Understand the role and importance of Markov Chain Monte Carlo in modern Bayesian methods
3 Understand how modern Bayesian models are fitted
4 Be able to fit Bayesian models to common types of study designs and data types
5 Know what aspects of the Bayesian analysis are an essential part of a statistical report
6 Have worked through some case studies (in lectures, tutorials and as part of assignments)
7 Have developed expertise in using the brms program within the R environment

_PRE-REQUISITES_

HAD5316H – Biostatistics II: Advanced Techniques in Applied Regression Methods, Some simple programming (e.g., SAS data step, R, S-Plus) – may be taken concurrently with course.

Necessary skills include: [installing packages](https://www.rdocumentation.org/packages/utils/versions/3.6.2/topics/install.packages), reading data into R, basic [data cleaning in R](https://www.youtube.com/watch?v=6PVMJE3HBN0) including basic data manipulation and graphics (e.g., plot or [ggplot2](https://ggplot2.tidyverse.org/)).


_EVALUATION_

4 Individual Assignments each worth 25%

 
## Course Textbook and Structure {-}

_TEXTBOOK_: 2nd edition of the book by Richard McElreath: https://xcelab.net/rm/statistical-rethinking/


The course will be organized into weekly lectures consisting of a combination of electronic slides and demonstrations. Students are expected to ask and answer questions in class. Classes will contain regular breaks for small group breakouts where small assignments will be given for students to complete together. The idea of these breakouts is to engage with your classmates and work through coding exercises together. Exercises will often be structured in a way that forces your group to go beyond what is included in the class notes and seek help online to figure out how to complete. Students should bring a laptop to in person class and be prepared to follow along with demonstrations and breakout groups.

Example assignments are shown below along with the associated core competency.

 
| Assignment | Competency |
|------------|------------|
| Properly install software for reproducible research: R, R Studio, homebrew (Mac), Git, text editor (e.g., Notepad++ or Sublime Text), LaTex, GNU make   | Identify software for the interface of data entry and statistical analysis |
| Build a GitHub repository, tag a release of your code, and write a proper README file | Develop public health information systems to support public health efforts |
| Develop an R Markdown document performing a reproducible statistical analysis and summarizing results visually | Apply standard statistical methods in the analysis of public health information Assess individual data elements and display results effectively and appropriately|
| Build a Docker container for running a fully reproducible analysis pipeline| Develop public health information systems to support public health efforts   |
| Execute basic python commands in a Jupyter notebook. | Identify software for the interface of data entry and statistical analysis   |
| Set up an EC2 instance and S3 bucket on AWS suitable for a reproducible data analysis in the cloud. | Develop public health information systems to support public health efforts |


## Accessibility and Accommodations {-}

## Honor Code {-}
You are bound by Emory University’s Student Honor and Conduct Code. RSPH requires that all material submitted by a student fulfilling his or her academic course of study must be the original work of the student.  Violations of academic honor include any action by a student indicating dishonesty or a lack of integrity in academic ethics. Academic dishonesty refers to cheating, plagiarizing, assisting other students without authorization, lying, tampering, or stealing in performing any academic work, and will not be tolerated under any circumstances.

The [RSPH Honor Code](http://www.sph.emory.edu/cms/current_students/enrollment_services/honor_code.html) states: "*Plagiarism is the act of presenting as one's own work the expression, words, or ideas of another person whether published or unpublished (including the work of another student). A writer’s work should be regarded as his/her own property.*" 


## Calendar and Outline {-}

| Date  | Topics                           |
|-------|----------------------------------|
| 1/  | Motivation, text editor          |
| 1/  | Command line                     |
| 1/  | Command line 					   |
| 1/  | R Markdown					   |
| 2/  | R Markdown                       |
| 2/  | Version control using Git/GitHub |
| 2/  | Git/GitHub + GNU Make            |
| 3/  | GNU Make 						   |
| 3/  | Best coding practices            |
| 3/  | Docker    					   |
| 4/  | Docker 						   |
| 4/  | Last assignment due 					   |



# Getting started with R and R studio {-}



